{% set version = "1.4.20" %}

package:
  name: menuinst
  version: {{ version }}

source:
  url: https://github.com/conda/menuinst/archive/{{ version }}.tar.gz
  sha256: 270e05c145cb417a662a13979f2273df4ccc7adb17a478b302d9e8592aec5a87

build:
  number: 1
  skip: true  # [not win]
  script:
    - {{ PYTHON }} -m pip install . -vv
    - copy "%SRC_DIR%\\cwp.py" "%PREFIX%\\"
  entry_points:
    - menuinst = menuinst.main:main
  skip_compile_pyc:
    - cwp.py

requirements:
  build:
    - {{ compiler('c') }}  # [win]
    - {{ compiler('cxx') }}  # [win]
    - {{ stdlib("c") }}  # [win]
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - menuinst
  commands:
    - menuinst --help

about:
  home: https://github.com/conda/menuinst
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: cross platform install of menu items
  dev_url: https://github.com/conda/menuinst
  doc_url: https://conda.github.io/menuinst

extra:
  recipe-maintainers:
    - goanpeca
    - jakirkham
    - carlodri
    - isuruf
