{% set version = "2.0.0" %}

package:
  name: menuinst
  version: {{ version }}

source:
  url: https://github.com/conda/menuinst/archive/{{ version }}.tar.gz
  sha256: 0ca844379c0d904cc1879f574c4d4320e89290e63e2f61e2996aebdd579d539e

build:
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION="{{ version }}"
  script:
    # Apparently these files make the post-build linkage analysis crash
    # and we should not need them on Windows
    - del /q "{{ SRC_DIR }}\\menuinst\\data\\osx_launcher_*"  # [win]
    - del /q "{{ SRC_DIR }}\\menuinst\\data\\appkit_launcher_*"  # [win]
    - {{ PYTHON }} -m pip install . -vv
    # menuinst v1 expects cwp.py in PREFIX; backwards compat fix
    - copy "%SP_DIR%\\menuinst\\_legacy\cwp.py" "%PREFIX%\\"  # [win]

  # entry_points:
  #   - menuinst = menuinst.main:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}  # [win]
    - {{ compiler('cxx') }}  # [win]
  host:
    - python
    - pip
  run:
    - python

test:
  requires:
    - conda
    - pytest
    - pytest-cov
    - pydantic <2.0a0
    - hypothesis
    - hypothesis-jsonschema
  source_files:
    - tests
  imports:
    - menuinst
  commands:
    - unset CI  # [unix]
    - set "CI="  # [win]
    - pytest --no-cov -vv -k "not elevation"

about:
  home: https://github.com/conda/menuinst/
  license: BSD-3-Clause AND MIT
  license_file:
    - LICENSE.txt
    - menuinst/_vendor/apipkg/LICENSE
  summary: cross platform install of menu items
  doc_url: https://conda.github.io/menuinst/

about:
  home: https://github.com/conda/menuinst/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: cross platform install of menu items

  dev_url: https://github.com/conda/menuinst
  doc_url: https://github.com/conda/menuinst/wiki

extra:
  recipe-maintainers:
    - goanpeca
    - jakirkham
    - carlodri
    - isuruf
    - jaimergp
