{% set version = "2.0.0" %}

package:
  name: menuinst
  version: {{ version }}

source:
  url: https://github.com/conda/menuinst/archive/{{ version }}.tar.gz
  sha256: 0ca844379c0d904cc1879f574c4d4320e89290e63e2f61e2996aebdd579d539e

build:
  number: 0
  skip: true  # [not win]
  script:
    - {{ PYTHON }} -m pip install . -vv
    - copy "%SRC_DIR%\\cwp.py" "%PREFIX%\\"
  entry_points:
    - menuinst = menuinst.main:main
  skip_compile_pyc:
    - cwp.py

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - menuinst

  commands:
    - menuinst --help

about:
  home: https://github.com/conda/menuinst/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: cross platform install of menu items

  dev_url: https://github.com/conda/menuinst
  doc_url: https://github.com/conda/menuinst/wiki

extra:
  recipe-maintainers:
    - goanpeca
    - jakirkham
    - carlodri
    - isuruf
