travis:
  secure:
    BINSTAR_TOKEN: dqMpuUeLl6Y5/ZJ00yGWmbACxFkV6P7hQ9rkFqA+ROBMzGVJAPZPEJLiLcvLrWxKZVCKpYKoVZY7mR1Mewp6bCzPlj+cN9X30uQQWPPZUwQ75OtIKLUwHnRxICVLaZx4Jhsxj52a75T/0uULOg82j9Fl5t3+wBcCzNIoXTcNg3Sed/XsjrJsjz3cBi6PQALJmtfTCTbpaL1yYidqZfwu0bqT3nlmL0oqb9H9axnYIdiabla5i1AfY5nJmPoHSwhQNhIi/MjYDyjV9q4U+sEeX/2wVKNZbH+huLr8UUlvtdF/ERpR+mlnZ5smxTPxCtMMyiiZ82veG7/CBwm2qM8uQiR+4TscIXkjTk5nbgx+Q2OjI1mCpukg4MKz+LEt8JaTF5mHrYsfTnxAgEyDClhzfvpaNVuLlou0llQ777tJQuKc3O5Aq7MC5sSMQqqMjdTG6rJBCecKNxQAK68VuxQTAQ/b/81foO/kIE9IQ/WxX9efJgQ611syJgUViedj2u/jVE/5yc+SBqjI+BEh63voinBpTAl9bM75eIr/zVvCmeNJptSFZQi4q026Y7gqaZhyV75yZhjYGNX9EtPa6UdDxEc5a0n5exRxxgDMzv1IhreM8pDp5wplPKnZcfwkPazBDqJNbZOi7n0JyHMNlTBro2nd8p4uPqsBPJQjKq0+L/Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
